#! /bin/sh

##
#       cdecl -- C gibberish translator
#       bootstrap
#
#       Copyright (C) 2021-2025  Paul J. Lucas
#
#       This program is free software: you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation, either version 3 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# Uncomment the following line for shell tracing.
#set -x

########## Functions ##########################################################

error() {
  echo $ME: $*
  exit 1
}

assert_exists() {
  for command in $*
  do
    command -v $command > /dev/null 2>&1 ||
      error "required command \"$command\" not in \$PATH"
  done
}

local_basename() {
  ##
  # Autoconf, 11.15:
  #
  # basename
  #   Not all hosts have a working basename. You can use expr instead.
  ##
  expr "//$1" : '.*/\(.*\)'
}

########## Begin ##############################################################

ME=`local_basename "$0"`

assert_exists autoreconf automake m4

echo "Generating \"configure\"..."
autoreconf -fi

# vim:set et sw=2 ts=2:
