.\"
.\"     cdecl -- C gibberish translator
.\"     cdecl.1: manual page
.\"
.\"     Copyright (C) 2017  Paul J. Lucas, et al.
.\"
.\"     This program is free software: you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation, either version 3 of the License, or
.\"     (at your option) any later version.
.\"
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\"
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" ---------------------------------------------------------------------------
.\" define code-start macro
.de cS
.sp
.nf
.RS 5
.ft CW
..
.\" define code-end macro
.de cE
.ft 1
.RE
.fi
.if !'\\$1'0' .sp
..
.\" ---------------------------------------------------------------------------
.TH \f3cdecl\fP 1 "April 30, 2017" "PJL TOOLS"
.SH NAME
cdecl, c++decl \- compose and decipher C & C++ declarations and casts
.SH SYNOPSIS
.B cdecl
.BI [ options ]
.BI [ file " " ... ]
.br
.B c++decl
.BI [ options ]
.BI [ file " " ... ]
.br
.B cast
.BI [ options ]
.I english
.br
.B declare
.BI [ options ]
.I english
.br
.B explain
.BI [ options ]
.I gibberish
.SH DESCRIPTION
\f2``I'm still uncertain about the language declaration syntax,
where in declarations,
syntax is used that mimics the use of the variables being declared.
It is one of the things that draws strong criticism,
but it has a certain logic to it.''\fP
.PD 0
.IP
\(em Dennis M. Ritchie

.P
.PD
.I ``I consider the C declarator syntax an experiment that failed.''
.PD 0
.IP
\(em Bjarne Stroustrup
.PD
.PP
.B cdecl
is a program for composing and deciphering C (or C++)
type declarations
or casts,
aka ``gibberish.''
It can be used interactively on a terminal
or accept input from either the command line or standard input.
.SH INVOCATION
.SS Executable Name
.B cdecl
may be invoked
under a number of different names
(by either renaming the executable
or creating either a symbolic or hard link to it).
If it is invoked as:
.TP 9
.B cdecl
Runs with the latest supported version of C as the default language.
.TP
.BR c++decl " | " cppdecl " | " cxxdecl
Runs with the latest supported version of C++ as the default language.
.TP
.BR cast " | " declare
Runs with the latest supported version of C as the current language
interpreting the rest of the command-line
(if given)
as pseudo-English,
performs the conversion to gibberish,
and exits.
.TP
.B explain
Runs with the latest supported version of C as the current language
interpreting the rest of the command-line
(if given)
as gibberish,
performs the conversion to pseudo-English,
and exits.
.P
For example
(where \f(CW$\fP is the shell prompt):
.cS
$ declare p as pointer to const pointer to const int
const int *const *p;
.cE
When using
.BR explain ,
care must be taken either to escape or quote shell metacharacters:
.cS
$ explain 'int *const (*p)[4]'
declare p as pointer to array 4 of const pointer to int
.cE 0
.SS First Argument
.B cdecl
will also behave as above
if the first non-option argument on the command-line
is one of
.BR cast ,
.BR declare ,
or
.BR explain :
.cS
$ cdecl declare p as pointer to array 4 of int
int (*p)[4];
.cE 0
.SS Standard Input
If no file names are given,
or a file name of ``\f(CW-\fP'' is encountered,
standard input will be read
until end-of-file is encountered
or either the
.BR exit ,
.BR q ,
or
.B quit
command is given.
.PP
You can use
.B cdecl
as you create a C (or C++) program from within an editor.
For example,
in
.BR vi (1),
type the declaration in pseudo-English,
then filter the line through
.BR cdecl :
.cS
!!cdecl<CR>
.cE
where \f(CW<CR>\fP is the
.I return
key.
.SS Interactive Input
If standard input is coming from a terminal
(or either the
.B \-\-interactive
or
.B \-i
option is specified),
a prompt of either
\f(CWcdecl>\fP
or
\f(CWc++decl>\fP
will be written to the terminal before each line of input.
The prompt can be turned off by either the
.B \-\-quiet
or
.B \-q
option,
or the
.B set noprompt
command.
.PP
.B cdecl
uses the GNU
.BR readline (3)
library
(if available and compiled in)
to provide keyword completion,
command-line history,
and
editing.
.SS File Input
.B cdecl
reads the named files for statements in the language described below.
A transformation is made from that language to C (or C++)
for either
.B cast
or
.BR declare ,
or pseudo-English
for
.BR explain .
The results of this transformation are written to standard output
(unless either the
.B \-o
or
.B \-\-output
option is given).
.SH OPTIONS
An option argument
.I f
means
.I file
and
.I s
means
.IR string .
.TP 4
.BI \-\-color \f1=\fPs "\f1 | \fP" "" \-c " s"
Sets when to colorize output to
.I s
(which is case-insensitive).
(See the
.B CDECL_COLORS
environment variable about colorization.)
The choices for
.I s
are:
.RS
.TP 11
.B always
Always colorize.
.TP
.B auto
Explicit synonym for
.BR isatty .
.TP
.B isatty
Colorize only when standard output is connected to a TTY
(terminal)
and the TERM environment variable
is not empty and not equal to
.BR dumb .
.TP
.B never
Never colorize.
.TP
.B not_file
Colorize only when
.I not
writing to a regular file
(hence writing to a TTY or pipe)
and the TERM environment variable
is not empty and not equal to
.BR dumb .
(Specifically,
.BR fstat (3)
is called on standard output:
colorize only if \f(CWS_IFREG\f1 is false.)
.IP ""
This is more useful than
.B isatty
since it accomodates the common case of allowing color output to be piped to
.BR less (1)
and still display in color since
.B less
understands
.I SGR
(``Select Graphic Rendition'')
ASCII terminal escape sequences
that produce color.
.TP
.B not_isreg
Explicit synonym for
.BR not_file .
.TP
.B tty
Synonym for
.BR isatty .
.RE
.IP ""
The default is
.BR not_file .
.TP
.BR \-\-debug " | " \-d
Turns on debugging output (if compiled in).
The additional JSON-like output is of an abstract syntax tree
as it is being constructed
from user input
while the parser is reducing grammar productions.
(This is a debugging aid for developers of
.B cdecl
itself.)
.TP
.BI \-\-file \f1=\fPf "\f1 | \fP" "" \-f " f"
Reads commands from file
.IR f .
.TP
.BR \-\-interactive " | " \-i
Forces interactive mode,
that is
turns on prompting
and
enables line-editing and history.
(This is the default when connected to a terminal.)
.TP
.BI \-\-language \f1=\fPs "\f1 | \fP" "" \-x " s"
Specifies which version of what language
.I s
(which is case-insensitive)
to use.
(See
.B C AND C++ LANGUAGE VERSIONS
for valid values of
.IR lang .)
The default is
.B C11
(for
.BR cdecl )
and
.B C++14
(for
.BR c++decl ).
.TP
.BR \-\-no-semicolon " | " \-s
Suppresses printing of a trailing semicolon for C (and C++) declarations.
.TP
.BI \-\-output \f1=\fPf "\f1 | \fP" "" \-o " f"
Sends all non-error output to file
.IR f .
.TP
.BR \-\-quiet " | " \-q
Be quiet by suppressing the prompt in interactive mode.
.TP
.BR \-\-version " | " \-v
Prints the version number to standard error
and exits.
.TP
.BR \-\-yydebug " | " \-y
Turns on
.BR bison (1)
debugging output
(if compiled in).
The additional output is of grammar productions
as they are being reduced by the parser.
(This is a debugging aid for developers of
.B cdecl
itself.)
.SH C AND C++ LANGUAGE VERSIONS
The argument to the
.B \-\-language
or
.B \-x
option
or the
.B set
command
is one of the following versions
(which are case-insensitive):
.TP 7
.B C
Use the latest supported version of the C language.
.TP
.BR CKNR " | " KNR " | " KNRC
Use the pre-ANSI Kernighan & Ritchie version of the C language
as given in the first edition of
.IR "The C Programming Language" .
.TP
.B C89
Use the C89 (first ANSI C) version of the C language.
Adds support for
\f(CWconst\fP,
\f(CWenum\fP,
\f(CWlong double\fP,
\f(CWsigned\fP,
\f(CWsize_t\fP,
\f(CWvoid\fP,
\f(CWvolatile\fP,
and function prototypes.
.TP
.B C95
Use the C95 version of the C language.
Adds support for
\f(CWwchar_t\fP.
.TP
.B C99
Use the C99 version of the C language.
Adds support for
\f(CW_Bool\fP (and \f(CWbool\fP),
\f(CW_Complex\fP (and \f(CWcomplex\fP),
\f(CWrestrict\fP,
and
\f(CWinline\fP
functions.
.TP
.B C11
Use the C11 version of the C language.
Adds support for
\f(CW_Atomic\fP,
\f(CWchar16_t\fP,
\f(CWchar32_t\fP,
\f(CW_Noreturn\fP
(and \f(CWnoreturn\fP),
and
\f(CW_Thread_local\fP
(and \f(CWthread_local\fP).
.TP
.B C++
Use the latest supported version of the C++ language.
.TP
.B C++98
Use the C++98 version of the C++ language.
Adds support for
\f(CWclass\fP,
references,
pointers to class members,
and \f(CWvirtual\fP functions.
.TP
.B C++03
Use the C++03 version of the C++ language.
Adds support for
\f(CWmutable\fP
data members.
.TP
.B C++11
Use the C++11 version of the C++ language.
Adds support for
\f(CWauto\fP,
\f(CWchar16_t\fP,
\f(CWchar32_t\fP,
\f(CWenum class\fP,
rvalue references,
\f(CWthread_local\fP,
the function trailing return-type syntax,
and
member function ref-qualfiers,
\f(CWfinal\fP,
and
\f(CWoverride\fP.
.TP
.B C++14
Use the C++14 version of the C++ language.
Adds support for
\f(CWauto\fP
functions.
.SH CDECL LANGUAGE
.SS Commands
.B cdecl
has the following commands:
.RS 4
.TP 4
.BI cast " name" " into" " english"
Composes a C (or C++) cast from pseudo-English.
.TP
.BI declare " name" " as" " english"
Composes a C (or C++) declaration from pseudo-English.
.TP
.BI explain " gibberish"
Deciphers a C (or C++) declaration into pseudo-English.
.TP
.BR "explain (" \f2gibberish\fP ")" [ \f2name\fP ]
Deciphers a C (or C++) cast into pseudo-English.
.TP
.BR set " [" \f2option\fP "] | " "set options"
In the first form,
sets a particular option, if given;
if not,
it's equivalent to the second form
that prints the current value of all options.
.TP
.BR help " | " ?
Prints a
.B cdecl
language summary
(see
.B English
below)
that's sensitive to the current programming language
(C or C++).
.TP
.BR exit " | " quit " | " q
Quits
.BR cdecl .
.RE
.P
Commands are terminated by either a semicolon or newline.
However,
commands may be given that span multiple lines
when newlines are escaped via \f(CW\\\fP.
When a newline is escaped,
the next prompt changes to either
\f(CWcdecl+\fP
or
\f(CWc++decl+\fP
to indicate that the current line
will be a continuation of the previons line.
.SS English
In what follows,
[] means zero or one,
* means zero or more,
{} means one of,
and
| means alternate.
The only punctuation characters used in pseudo-English
are parentheses around
and commas between
function (or block) arguments.
.P
.I English
is one of:
.IP "" 4
.RB [ \f2storage\fP "]* " array " [" \f2number\fP "] " of " \f2english\fP"
.br
.BR block " [" ( [ \f2args\fP ] ) "] [" returning " \f2english\fP" "" "]"
.br
.RB [ \f2storage\fP "]* [" \f2fn-qualifier\fP "]* " function " [" ( [ \f2args\fP ] ) "] [" returning " \f2english\fP" "" "]"
.br
.RB [ \f2cv-qualifier\fP "]* " "pointer to" " [" "member of class" " \f2name\fP" "" ] " \f2english\fP"
.br
.RB [ rvalue "] " "reference to" " \f2english\fP"
.br
.I type
.P
and
.I type
is either:
.IP "" 4
.RI [ storage "]* [" modifier "]* [" C-type ]
.br
.RB "{ " enum " [" class " | " struct "] | " class " | " struct " | " union " } \f2name\fP"
.P
where:
.RS 4
.TP 14
.I args
A comma-separated list of
.IR name ,
.IR english ,
.I name
\f(CWas\fP
.IR english ;
or one of
\f(CWvarargs\fP,
\f(CWvariadic\fP,
or
\f(CW...\fP
(ellipsis).
.TP
.I C-type
One of:
\f(CWauto\fP (C++11 or later),
\f(CWbool\fP,
\f(CWchar\fP,
\f(CWchar16_t\fP,
\f(CWchar32_t\fP,
\f(CWwchar_t\fP,
\f(CWint\fP,
\f(CWsize_t\fP,
\f(CWfloat\fP,
\f(CWdouble\fP,
or
\f(CWvoid\fP.
.TP
.I cv-qualifier
One of:
\f(CW_Atomic\fP,
\f(CWconst\fP,
\f(CWrestrict\fP,
or
\f(CWvolatile\fP.
.TP
.I fn-qualifier
One of:
\f(CWconst\fP,
\f(CWreference\fP,
\f(CWrvalue reference\fP,
or
\f(CWvolatile\fP.
.TP
.I modifier
One of:
\f(CWshort\fP,
\f(CWlong\fP,
\f(CWsigned\fP,
\f(CWunsigned\fP,
or
\f(CWcomplex\fP.
.TP
.I name
A valid C (or C++) identifier.
.TP
.I number
One of a
decimal,
octal (if starting with \f(CW0\fP),
hexadecimal (if starting with either \f(CW0x\fP or \f(CW0X\fP),
or
binary (if starting with either \f(CW0b\fP or \f(CW0B\fP)
number.
.TP
.I storage
One of:
\f(CWauto\fP (C, or C++03 or earlier),
\f(CWblock\fP,
\f(CWconstexpr\fP,
\f(CWextern\fP,
\f(CWfinal\fP,
\f(CWfriend\fP,
\f(CWinline\fP,
\f(CWmutable\fP,
\f(CWnoreturn\fP,
\f(CWoverride\fP,
\f(CWregister\fP,
\f(CWstatic\fP,
\f(CWthread_local\fP,
\f(CWtypedef\fP,
\f(CWvirtual\fP,
or
\f(CWpure virtual\fP.
.RE
.P
If
.B returning
.I english
is omitted,
it's equivalent to
.BR "returning void" .
.SS Synonyms
Some synonyms are permitted within pseudo-English.
The words on the left are synonyms for what's on the right:
.cS
       atomic  _Atomic
    automatic  auto
        _Bool  bool
    character  char
     _Complex  complex
     constant  const
  enumeration  enum
         func  function
      integer  int
          mbr  member
non-returning  noreturn
    _Noreturn  noreturn
   overridden  override
          ptr  pointer
          ref  reference
   restricted  restrict
          ret  returning
    structure  struct
         type  typedef
_Thread_local  thread_local
      varargs  ...
     variadic  ...
       vector  array
.cE 0
.SS Gibberish
.I Gibberish
is any supported C
(for
.BR cdecl )
or C++
(for
.BR c++decl )
variable or function declaration,
or type cast.
(See
.B EXAMPLES
for examples
and
.B CAVEATS
for unsupported declarations.)
.P
.I Gibberish
also includes support
for Apple's ``blocks'' syntax
and
\f(CW__block\fP
storage class.
.SS Set Options
The
.B set
command takes several options:
.RS 4
.TP 6
.I lang
Use
.I lang
(which is case-insensitive)
as the current language.
(See
.B C AND C++ LANGUAGE VERSIONS
for valid values of
.IR lang .)
.TP
.RB [ no ] debug
Turns [off] or on debugging output
(if compiled in)
\(em default is off.
.TP
.B options
Prints the current value of all options.
.TP
.RB [ no ] prompt
Turns [off] or on the prompt
\(em default is on.
.TP
.RB [ no ] semicolon
Turns [off] or on printing a semicolon at the end of a C (or C++) declaration
\(em default is on.
.TP
.RB [ no ] yydebug
Turns [off] or on
.BR bison (1)
debugging output
(if compiled in)
\(em default is off.
.RE
.SH EXAMPLES
To declare an array of pointers to functions that are like
.BR malloc (3):
.cS
cdecl> declare fptab as array of pointer to function \\
cdecl+     returning pointer to char
char *(*fptab[])();
.cE
When you see this declaration in someone else's code,
you can make sense out of it by doing:
.cS
explain char *(*fptab[])()
.cE
The proper declaration for
.BR signal (2),
ignoring function prototypes,
is easily described in
.BR cdecl 's
language:
.cS
cdecl> declare signal as function \\
cdecl+     returning pointer to function returning void
void (*signal())()
.cE
The function declaration that results has two sets of empty parentheses.
The author of such a function might wonder where to put the parameters:
.cS
cdecl> declare signal as function (sig, func) \\
cdecl+     returning pointer to function returning void
void (*signal(sig,func))();
.cE
If we want to add in the function prototypes,
the function prototype for a function such as
.BR _exit (2)
would be declared with:
.cS
cdecl> declare _exit as function (retvalue as int) returning void
void _exit(int retvalue);
.cE
As a more complex example using function prototypes,
.BR signal (2)
would be fully defined as:
.cS
cdecl> declare signal as function \\
cdecl+     (sig as int, \\
cdecl+      f as pointer to function (int) returning void) \\
cdecl+     returning pointer to function (int) returning void
void (*signal(int sig, void (*f)(int)))(int);
.cE
.B cdecl
can help figure out where to put
\f(CWconst\fP and \f(CWvolatile\fP modifiers:
.cS
cdecl> declare pc as pointer to const int
const int *pc;

cdecl> declare cp as const pointer to int
int *const cp;
.cE
.B c++decl
can help with declaring references:
.cS
c++decl> declare rp as reference to pointer to char
char *&rp;
.cE
.B c++decl
can help with pointers to member of classes:
.cS
c++decl> declare p as pointer to member of class C int
int C::*p;
.cE
and:
.cS
c++decl> declare p as pointer to member of class C \\
c++decl+     function (i as int, j as int) \\
c++decl+     returning pointer to class D
class D *(C::*p)(int i, int j)
.cE 0
.SH EXIT STATUS
.PD 0
.IP 0
Success.
.IP 64
Command-line usage error.
.IP 65
Syntax or semantic error.
.IP 66
Open file error.
.IP 70
Internal software error.
(Please report the bug.)
.IP 71
System error.
.IP 73
Create file error.
.IP 74
I/O error.
.PD
.SH ENVIRONMENT
.TP 4
.B CDECL_COLORS
This variable specifies the colors and other attributes
used to highlight various parts of the output
in a manner similar to the
.B GCC_COLORS
variable
used by
.BR gcc .
.IP ""
As with
.BR gcc ,
the value is composed of a colon-separated sequence of capabilities.
Each capability is of the form
.IR name [= SGR ]
where
.I name
is a capability name
and
.IR SGR ,
if present,
is a
``Select Graphic Rendition''
value
that is a semicolon-separated list of integers
in the range 0\-255.
An example SGR value is \f(CW31;1\f1
that specifies a bright red foreground
on the terminal's default background.
.IP ""
Capability names in upper-case are unique to
.BR cdecl ;
those in lower-case are upwards compatibile with
.BR gcc .
.RS
.TP 18
.BI caret= SGR
SGR for the caret pointing to the error on the line above
(as with
.BR gcc ).
The default is \f(CW36;1\f1
(bright green foreground over current terminal background).
.TP
.BI error= SGR
SGR for the word ``error.''
The default is \f(CW31;1\f1
(bright red foreground over current terminal background).
.TP
.BI HELP-keyword= SGR
SGR for keywords in help output.
The default is \f(CW1\f1
(bold terminal foreground current terminal background).
.TP
.BI HELP-nonterm= SGR
SGR for nonterminals in help output.
The default is \f(CW36\f1
(cyan foreground over current terminal background).
.TP
.BI HELP-punct= SGR
SGR for punctuation in help output.
The default is \f(CW30;1\f1
(dark dray forgreound over current terminal background).
.TP
.BI HELP-title= SGR
SGR for titles in help output.
The default is \f(CW34;1\f1
(bright blue foreground over current terminal background).
.TP
.BI locus= SGR
SGR for location information in error and warning messages.
The defualt is \f(CW1\fP
(bold current foreground over current terminal background).
.TP
.BI PROMPT= SGR
SGR for the prompt.
The default is \f(CW32\f1
(green foreground over current terminal background).
.TP
.BI warning= SGR
SGR for the word ``warning.''
The default is \f(CW33;1\f1
(bright yellow foreground over current terminal background).
.RE
.IP ""
Other
.B gcc
capabilities, if present, are ignored
because they don't apply in
.BR cdecl .
The term ``color'' is used loosely.
In addition to colors,
other character attributes
such as bold, underlined, reverse video, etc.,
may be possible depending on the capabilities of the terminal.
.TP
.B COLUMNS
The number of columns of the terminal on which
.B cdecl
is being run.
Used to get the terminal's width
for limiting error and warning messages' length.
Takes precedence over the number of columns specified by the
.B TERM
variable.
.TP
.B GCC_COLORS
This variable is used for compatibility with
.BR gcc .
It is used exactly as
.B CDECL_COLORS
but only when
.B CDECL_COLORS
is either unset or empty.
Capabilities in
.B gcc
that are unsupported by
.B cdecl
(because they don't apply)
are ignored.
.TP
.B TERM
The type of the terminal on which
.B cdecl
is being run.
.SH FILES
.TP 4
.B ~/.inputrc
Individual
.BR readline (3)
initialization file.
.SH BUGS
On macOS (up through to at least version 10.12, aka
.IR Sierra ),
the
.BR readline (3)
API is provided,
but backed by
.B libedit
that has a bug that prevents color prompts from working correctly.
As such,
the
.B PROMPT
color cabapility is ignored on systems
that do not provide genuine GNU
.BR readline (3).
.SH CAVEATS
.SS Unsupported Declarations
The following types of declarations are not currently supported:
.nr step 1 1
.IP \n[step]. 3
Multiple comma-separated declarations are not supported:
.cS
int i, *p;                        // not supported
.cE 0
.IP \n+[step].
Only
\f(CWenum\fP,
\f(CWclass\fP,
\f(CWstruct\fP,
and
\f(CWunion\fP
names are supported;
complete declarations are not:
.cS
struct S s;                       // supported
struct S { int i; char c; } s;    // not supported
.cE 0
.IP \n+[step].
The C11 (and C++11)
\f(CWalignas\fP specifier
is not supported.
.IP \n+[step].
Qualified C++ data members or member functions,
or member functions that are deleted
are not supported:
.cS
int C::x;                         // not supported
int C::f();                       // not supported
int g() = delete;                 // not supported
.cE 0
.IP \n+[step].
C++
constructors,
destructors,
attribute specifiers
(e.g., \f(CW[[noreturn]]\fP),
\f(CWdecltype\fP,
function default arguments
and exception specifications
(\f(CWthrow()\fP and \f(CWnoexcept\fP),
overloaded operators,
and
template declarations
are not supported.
.SS Other Minor Caveats
.nr step 1 1
.IP \n[step]. 3
When converting from pseudo-English to a C++ declaration,
\f(CWenum\fP,
\f(CWclass\fP,
\f(CWstruct\fP,
and
\f(CWunion\fP
types include the corresponding keyword explicitly in the result
even though it isn't needed in C++:
.cS
c++decl> declare p as pointer to struct S
struct S *p;
.cE 0
.IP ""
This is because,
when going the other way from a C++ declaration to pseudo-English,
the declaration parser can't know that an arbitrary name,
in this example, \f(CWS\fP, is one of an
\f(CWenum\fP,
\f(CWclass\fP,
\f(CWstruct\fP,
or
\f(CWunion\fP
name.
While the keyword
.I could
be elided from the output of
.BR declare ,
it isn't in order to have the output be ``round-trippable''
when used as input to
.BR explain .
.IP \n+[step].
When converting from pseudo-English to a C++ declaration
for either
\f(CWauto\fP,
or a reference or an rvalue reference variable
that is not a function argument,
the output doesn't include an initializer:
.cS
c++decl> declare x as auto
auto r;
c++decl> declare r as reference to int
int &r;
.cE 0
.IP ""
These are illegal C++ declarations
since
\f(CWauto\fP
and such references
.I must
be initialized.
.IP \n+[step].
While
.B explain
supports the C++11 function trailing return-type syntax,
.B declare
always prints in the traditional syntax.
.SH AUTHORS
.B cdecl
has been around since the mid-1980s
and there have been many versions of
.BR cdecl ,
some with different subsets of authors.
This list is a best-effort at a union of all authors.
In reverse chronological order:
.P
.BI "Paul J. Lucas <" paul@lucasmail.org ">"
.br
.BI "Peter Ammon <" cdecl@ridiculousfish.com ">"
.br
.BI "David R. Conrad <" conrad@detroit.freenet.org ">"
.br
.BI "Alexander Dupuy <" dupuy@cs.columbia.edu ">"
.br
.BI "Merlyn LeRoy <" merlyn@rose3.rosemount.com ">"
.br
.BI "Tony Hansen <" tony@attmail.com ">"
.br
.BI "David Wolverton <" david_wolverton@att.com ">"
.br
.B Graham Ross
.SH SEE ALSO
.BR bison (1),
.BR clang (1),
.BR gcc (1),
.BR vi (1),
.BR yacc (1),
.BR isatty (3),
.BR readline (3),
.BR sysexits (3)
.\" vim:set et sw=2 ts=2:
